apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: event
        image: ginsp/events:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: event-srv
spec:
    type: ClusterIP
    selector:
        app: event
    ports:
    - name: event
      port: 4005
      targetPort: 4005


