apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: gins/posts:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
